[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="alexjuma10"

[auth.google]
client_id="480983513832-8qf1e7m9t2ciucgvpg88a82j60kjeta2.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="https://accounts.google.com/.well-known/openid-configuration"

[database]
driver = "{ODBC Driver 18 for SQL Server}"
server = "stream-server.database.windows.net"
database = "streamlit_db2"
uid = "alexjuma"
pwd = "Aj37024013"
encrypt = "yes"                          
trust_server_certificate = "yes"

[gemini]
api_key = "AIzaSyCUUhK6bngglPni-WOPCmTINAetFiisbnk"
